import type { Job } from "@/types";

export const MOCK_JOBS: Array<Job & { match_score: number; matched_skills: string[]; missing_skills: string[] }> = [
  {
    id: "mock-1",
    job_hash: "mock-1",
    title: "Senior Frontend Engineer",
    company: "Stripe",
    company_logo_url: null,
    location: "Bangalore, India",
    is_remote: true,
    job_type: "full-time",
    experience_required: "3-5 years",
    salary_min: 2500000,
    salary_max: 4500000,
    salary_currency: "INR",
    skills_required: ["React", "TypeScript", "Next.js", "GraphQL", "TailwindCSS", "Jest"],
    description: "Build delightful, high-performance UIs for Stripe's dashboard and merchant tools.",
    source_platform: "LinkedIn",
    original_url: "https://stripe.com/jobs",
    posted_at: new Date(Date.now() - 86400000).toISOString(),
    fetched_at: new Date().toISOString(),
    is_active: true,
    match_score: 87,
    matched_skills: ["React", "TypeScript", "TailwindCSS"],
    missing_skills: ["GraphQL"],
  },
  {
    id: "mock-2",
    job_hash: "mock-2",
    title: "Full-Stack Developer (Internship)",
    company: "Razorpay",
    company_logo_url: null,
    location: "Remote",
    is_remote: true,
    job_type: "internship",
    experience_required: "Fresher",
    salary_min: 40000,
    salary_max: 60000,
    salary_currency: "INR",
    skills_required: ["Node.js", "React", "PostgreSQL", "Docker"],
    description: "Help build payment infrastructure used by millions of businesses.",
    source_platform: "Indeed",
    original_url: "https://razorpay.com/jobs",
    posted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    fetched_at: new Date().toISOString(),
    is_active: true,
    match_score: 72,
    matched_skills: ["Node.js", "React"],
    missing_skills: ["Docker", "PostgreSQL"],
  },
  {
    id: "mock-3",
    job_hash: "mock-3",
    title: "AI/ML Engineer",
    company: "Sarvam AI",
    company_logo_url: null,
    location: "Bangalore",
    is_remote: false,
    job_type: "full-time",
    experience_required: "2-4 years",
    salary_min: 3000000,
    salary_max: 6000000,
    salary_currency: "INR",
    skills_required: ["Python", "PyTorch", "LLMs", "CUDA", "Distributed Training"],
    description: "Train and deploy foundation models for Indian languages.",
    source_platform: "Wellfound",
    original_url: "https://sarvam.ai/careers",
    posted_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    fetched_at: new Date().toISOString(),
    is_active: true,
    match_score: 54,
    matched_skills: ["Python"],
    missing_skills: ["PyTorch", "CUDA", "LLMs"],
  },
];